import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Sidebar from "./Components/Sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-bg`}
      >
        <div className="flex">
          <div className="hidden md:block">
            <Sidebar />
          </div>
          <div className="flex-1">
            <Navbar />
           <div className="pt-5 px-10 text-text-primary">
             {children}
           </div>
          </div>
        </div>
      </body>
    </html>
  );
}
